#!/bin/bash
# Validate SKILL.md files — frontmatter, AUTO-DISCOVERY block, structure
# Usage: ./scripts/validate.sh
# Exit code: 0 = all pass, 1 = failures found

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FAIL=0
PASS=0
WARN=0

red()   { printf "\033[31m%s\033[0m\n" "$1"; }
green() { printf "\033[32m%s\033[0m\n" "$1"; }
yellow(){ printf "\033[33m%s\033[0m\n" "$1"; }

check_skill() {
  local file="$1"
  local name=$(basename "$(dirname "$file")")
  local parent=$(basename "$(dirname "$(dirname "$file")")")
  if [ "$parent" = "_internal" ]; then
    name="_internal/$name"
  fi

  # 1. YAML frontmatter exists (starts with ---)
  if ! head -1 "$file" | grep -q "^---$"; then
    red "FAIL: $name — missing YAML frontmatter (no opening ---)"
    FAIL=$((FAIL + 1))
    return
  fi

  # 2. Frontmatter has closing ---
  local fm_end=$(tail -n +2 "$file" | grep -n "^---$" | head -1 | cut -d: -f1)
  if [ -z "$fm_end" ]; then
    red "FAIL: $name — unclosed YAML frontmatter (no closing ---)"
    FAIL=$((FAIL + 1))
    return
  fi

  # 3. Required frontmatter fields: name, description
  local fm=$(head -$((fm_end + 1)) "$file")
  if ! echo "$fm" | grep -q "^name:"; then
    red "FAIL: $name — frontmatter missing 'name' field"
    FAIL=$((FAIL + 1))
    return
  fi
  if ! echo "$fm" | grep -q "^description:"; then
    red "FAIL: $name — frontmatter missing 'description' field"
    FAIL=$((FAIL + 1))
    return
  fi

  # 4. AUTO-DISCOVERY block exists
  if ! grep -q "^## AUTO-DISCOVERY" "$file"; then
    if ! grep -q "^> .*AUTO-DISCOVERY" "$file"; then
      yellow "WARN: $name — no AUTO-DISCOVERY section found"
      WARN=$((WARN + 1))
    fi
  fi

  # 5. AUTO-DISCOVERY has Identification sub-block
  if grep -q "^### Identification" "$file"; then
    # Check required fields in Identification
    local id_section=$(sed -n '/^### Identification/,/^### /p' "$file")
    if ! echo "$id_section" | grep -q "^name:"; then
      yellow "WARN: $name — AUTO-DISCOVERY Identification missing 'name'"
      WARN=$((WARN + 1))
    fi
    if ! echo "$id_section" | grep -q "^category:"; then
      yellow "WARN: $name — AUTO-DISCOVERY Identification missing 'category'"
      WARN=$((WARN + 1))
    fi
  fi

  # 6. No AI attribution leaks in skill content
  # Skip lines that are instructional (contain NEVER, don't, no, not — telling users to avoid attribution)
  if grep -i "co-authored-by:.*anthropic\|generated by claude\|generated by ai" "$file" 2>/dev/null \
     | grep -ivq "never\|don't\|no \|not \|avoid\|CLEAN\|FOUND\|check\|search\|grep\|filter"; then
    red "FAIL: $name — AI attribution leak found in skill content"
    FAIL=$((FAIL + 1))
    return
  fi

  green "PASS: $name"
  PASS=$((PASS + 1))
}

echo "=== wando-skills SKILL.md Validation ==="
echo ""

# Find all SKILL.md files
for skill in "$ROOT"/skills/*/SKILL.md; do
  [ -f "$skill" ] && check_skill "$skill"
done
for skill in "$ROOT"/skills/_internal/*/SKILL.md; do
  [ -f "$skill" ] && check_skill "$skill"
done

echo ""
echo "=== Results ==="
echo "PASS: $PASS  WARN: $WARN  FAIL: $FAIL"
echo "Total: $((PASS + WARN + FAIL)) skills checked"

if [ "$FAIL" -gt 0 ]; then
  red "VALIDATION FAILED"
  exit 1
else
  green "VALIDATION PASSED"
  exit 0
fi
